applications:
- name: vz-boss-dev
  memory: 512M 
  instances: 1
  host: vz-boss-dev
  domain: cfapps.io
  path: .
  buildpack: https://github.com/cloudfoundry/php-buildpack.git#8c13f5434b2f31ca960d2bca9153df1978258535
  services:
  - my-test-mysql-db 
